### ISSUE TITLE
Cần một endpoint có format: https://rest-sifoni-anhnt0212.c9.io/api/v1/register

### ISSUE THREAD

**Issue by tanUIT** [anhnt0212/rest-sifoni#2]
- Client sẽ gửi lên chuỗi json gồm 3 tham số: username, email, password
- Cần server trả về một token nếu thêm thành công user mới, hoặc trả về error nếu như user đã tồn tài

**Comment by anhnt0212** [comment]
Oh sr để update liền

**Comment by khanhicetea** [comment]
:+1:
